default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  username: dot_web_app
  password: K7Ui9b.s6^-U4fp
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: dot_development

test:
  <<: *default
  database: dot_test

production:
  <<: *default
  database: dot_production
