default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  username:
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database:

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database:
