default: &default
  api_url: localhost
  api_port: 3000
  api_ssl: false

development:
  <<: *default

test:
  <<: *default

production:
  api_url: <%= ENV['api_url'] %>
  api_port: <%= ENV['api_port'] %>
  api_ssl: false
