module ApplicationHelper
  def codes
    {
      '0' => 'Tornado',
      '1' => 'Tropical storm',
      '2' => 'Hurricane',
      '3' => 'Severe thunderstorms',
      '4' => 'Thunderstorms',
      '5' => 'rain-mix',
      '6' => 'Mixed rain and sleet',
      '7' => 'Mixed snow and sleet',
      '8' => 'Freezing drizzle',
      '9' => 'Drizzle',
      '10' => 'Freezing rain',
      '11' => 'showers',
      '12' => 'showers',
      '13' => 'Snow flurries',
      '14' => 'Light snow showers',
      '15' => 'Blowing snow',
      '16' => 'Snow',
      '17' => 'Hail',
      '18' => 'Sleet',
      '19' => 'Dust',
      '20' => 'fog',
      '21' => 'Haze',
      '22' => 'Smoky',
      '23' => 'Blustery',
      '24' => 'Windy',
      '25' => 'Cold',
      '26' => 'cloudy',
      '27' => 'Mostly cloudy (night)',
      '28' => 'Mostly cloudy (day)',
      '29' => 'Partly cloudy (night)',
      '30' => 'Partly cloudy (day)',
      '31' => 'Clear (night)',
      '32' => 'sunny',
      '33' => 'night-clear',
      '34' => 'day-cloudy',
      '35' => 'Mixed rain and hail',
      '36' => 'Hot',
      '37' => 'Isolated thunderstorms',
      '38' => 'Scattered thunderstorms',
      '39' => 'thunderstorms',
      '40' => 'Scattered showers',
      '41' => 'Heavy snow',
      '42' => 'Scattered snow showers',
      '43' => 'Heavy snow',
      '44' => 'Partly cloudy',
      '45' => 'Thundershowers',
      '46' => 'Snow showers',
      '47' => 'Isolated thundershowers',
      '3200' => 'Not available'
    }
  end
end
